# Generated by Django 5.0.3 on 2024-03-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorra',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='pantalon',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='remera',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='zapatilla',
            name='imagen',
        ),
    ]
